version: '3'
services:
  dataBase:
    image: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: financial
      MYSQL_ROOT_PASSWORD: root
